// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs-4njhATVxNbFQ6olGRoluTsewsp-gjM',
    appId: '1:753349279660:web:da2a7839b78f68449fc409',
    messagingSenderId: '753349279660',
    projectId: 'mes-evenements-73ae9',
    authDomain: 'mes-evenements-73ae9.firebaseapp.com',
    storageBucket: 'mes-evenements-73ae9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtcJFr2FQKDQvmAWGq-kDVk8OET1_iRVU',
    appId: '1:753349279660:android:2d757e9bc97237209fc409',
    messagingSenderId: '753349279660',
    projectId: 'mes-evenements-73ae9',
    storageBucket: 'mes-evenements-73ae9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA6wWGvNyLA4dERFbRZHqUvh8B31bDqew',
    appId: '1:753349279660:ios:09ffe2bbc70d34619fc409',
    messagingSenderId: '753349279660',
    projectId: 'mes-evenements-73ae9',
    storageBucket: 'mes-evenements-73ae9.firebasestorage.app',
    iosBundleId: 'com.enidedjender.mesEvenements',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA6wWGvNyLA4dERFbRZHqUvh8B31bDqew',
    appId: '1:753349279660:ios:fa52e0200a490b549fc409',
    messagingSenderId: '753349279660',
    projectId: 'mes-evenements-73ae9',
    storageBucket: 'mes-evenements-73ae9.firebasestorage.app',
    iosBundleId: 'com.example.mesEvenements',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCs-4njhATVxNbFQ6olGRoluTsewsp-gjM',
    appId: '1:753349279660:web:3c1c882bd395348d9fc409',
    messagingSenderId: '753349279660',
    projectId: 'mes-evenements-73ae9',
    authDomain: 'mes-evenements-73ae9.firebaseapp.com',
    storageBucket: 'mes-evenements-73ae9.firebasestorage.app',
  );
}
